### ISSUE TITLE
Handle more image formats

### ISSUE THREAD

**Issue by ProLoser** [jrbasso/MeioUpload#1]
It seems thumbnails of the original meio upload behavior can't be made from gifs or bmps? Any way to add support for these?

**Comment by jrbasso** [comment]
Jose Gonzalez changed the thumbnail generation. Now it's use PHPThumb to this. In phpthumb site, they say:

Supported source image formats:
    \* JPEG (via GD or ImageMagick)
    \* PNG (via GD or ImageMagick)
    \* GIF (via GD, ImageMagick, or phpthumb.gif.php)
    \* BMP (via ImageMagick or phpthumb.bmp.php)
    \* any image format ImageMagick can read

Supported output image formats:
    \* JPEG (via GD or ImageMagick)
    \* PNG (via GD or ImageMagick)
    \* GIF (via GD or ImageMagick)
    \* BMP (via ImageMagick or phpthumb.bmp.php)
    \* ICO (via ImageMagick or phpthumb.ico.php)

**Comment by josegonzalez** [comment]
I've yet to have it automatically do GIF or BMP files. Should just be a change in the beforeSave() and the generateThumbnail() . I'll take a look at it now.

**Comment by josegonzalez** [comment]
Seems to work for GIF images on my server in my "experimental" branch, which is a run of the mill PHP5.3 install. YMMV.
