### ISSUE TITLE
Delete file when edit a related model

### ISSUE THREAD

**Issue by viniciusbig** [jrbasso/MeioUpload#100]
There is possible delete files on edit record?

for example:
Post has images.
when I edit a post, can I mark a image do delete?

thank you, in advance

**Comment by jrbasso** [comment]
Yes, take a look on https://github.com/jrbasso/MeioUpload/wiki/Deleting-Existing-Uploads

You are welcome

**Comment by viniciusbig** [comment]
nothings happens!
the image is not erased

the field is
<?php echo $form->input('Nota.filename.remove', array(
    'type' => 'checkbox',
    'div' => false,
    'format' => array('between', 'input', 'after')); 
?>

and the $this->data 

Array
(
    [Post] => Array
        (
            [id] => 1
            [data] => 01/05/2012
            [texto] => teste teste teste teste 
        )
    [Imagem] => Array
        (
            [filename] => Array
                (
                    [remove] => 1
                )
        )
)

but the image remains in the database and files in the folder.
BTW, I'm using cake 1.3

PS: I can write here in Portuguese?
is much easier! ;]
