### ISSUE TITLE
Error MeioUpload plugin

### ISSUE THREAD

**Issue by f34nor** [jrbasso/MeioUpload#104]
I copied the MeioUploadBehavioren model/MeioUploadBehavior, and I copied the variable in my model "ProductosController", when load the page, produced error:

Error: The application is trying to load a file from the MeioUpload plugin

Error: Make sure your plugin MeioUpload is in the app/Plugin directory and was loaded

Loading all plugins: If you wish to load all plugins at once, use the following line in your app/Config/bootstrap.php file

Notice: If you want to customize this error message, create app/View/Errors/missing_plugin.ctp

In my  app/Config/bootstrap.php put: "CakePlugin::load('MeioUpload');"

HELP What is wrong?

Grettings

**Comment by jrbasso** [comment]
Follow the installation process (https://github.com/jrbasso/MeioUpload#installation). You copied the file to the wrong place. There is 3 options that you can do.
