### ISSUE TITLE
Call to undefined method FileGrabberBehavior::invalidate()

### ISSUE THREAD

**Issue by benjaminallison** [jrbasso/MeioUpload#108]
I had to change line 3 in FileGrabber as I'm using 2.3 and (I assume) the location of HttpSocket changed:

`App::uses('HttpSocket', 'Network/Http');`

But now I'm getting another error:

`Call to undefined method FileGrabberBehavior::invalidate()`

**Comment by jrbasso** [comment]
Seems you are in a wrong project. This behavior is not on this project.

**Comment by benjaminallison** [comment]
Wow sorry about both of those. I indeed thought I was on another project!

**Comment by josegonzalez** [comment]
Lolol I thought this was in my repo.
