### ISSUE TITLE
Cannot use any fieldname other than filename

### ISSUE THREAD

**Issue by ProLoser** [jrbasso/MeioUpload#11]
In my environment I have been able to narrow down the issues to only models that use custom field names for the file field, occasionally using more than 1 field to store file references. No other inputs are used or are present in the forms, and for my other models that simply have a filename field, uploading still works normally (on the latest version of the plugin, environment and all setup correctly).

**Comment by ProLoser** [comment]
This error is larger than I thought, I use this behavior in several models (ChoirSong and Scroll), scroll uses the 'filename' field. I ran debug($this->__fields);die; on line 256 of the behavior, immediately after triggering the validate method, and it appears that when attempting to save the choir song model, that variable no longer has the proper information for choir_song, instead it gives me this: http://bin.cakephp.org/view/1986685492 which is (due to the dir path i customized) actually coming from a later loaded model, the scroll model. Luckily I manually input the save location as I wasn't sure if this new behavior would save to ModelName or model_name folders.

**Comment by ProLoser** [comment]
Further consideration, I realized that in fact Scroll and ChoirSong are absolutely in no way related (none of my tables for this app have relationships), however this is located in my app_controller for use in the navigation bar: 

<pre><code>$this->set('latestScroll', $this->Scroll->find('first', array('recursive' => -1, 'order' => 'Scroll.published DESC')));</code></pre>

strangely when I wrote this app that code was located in beforeFilter, I relocated to beforeRender and am checking the results now.

This did not appear to resolve the problem, the debug of $this->__fields is still showing the relevant array for Scroll.

**Comment by ProLoser** [comment]
For now to resolve my issues I created a simple if-statement in the app_controller's beforeRender and updated the usage of $uses = array('Scroll') in the app_controller to CR::init() instead which resolved the problem due to the lack of need for the navigation item in admin layout.

Oddly enough I'm still getting issues about saving an array as a string. I'll continue researching.

**Comment by ProLoser** [comment]
I just closed the validation ticket, apparently I need to reopen it. The issue is caused because in ChoirSong, i have 3 potential file upload slots. however all of them are optional and I have been testing by filling in 1 and leaving the other two blank. The uploaded file works fine and saves as a string, however despite validation rules, the other two are attempting to save arrays. This is my model and the resultant errors: http://bin.cakephp.org/view/2133175775
notice the values for the 4-6 fields.

**Comment by ProLoser** [comment]
Hmm... did a bit more jumping around. should line 283 inside the beforeSave:
$this->data = $result['data'];
be
$model->data = $result['data'];
? I was trying to track down why it's saving arrays when the fields should be unset.

**Comment by josegonzalez** [comment]
How about making us some unit tests? Jump-start that front for us? :D

**Comment by ProLoser** [comment]
My last commit which iterates through fields properly fixes this ticket, you can close it.

**Comment by jrbasso** [comment]
Merged and closed...
