### ISSUE TITLE
Models are not being namespaced

### ISSUE THREAD

**Issue by ProLoser** [jrbasso/MeioUpload#12]
Can be recreated by putting multiple meio_upload models into $uses, only the very last model is saved under $this->__fields; debug($this->__fields); after line 245 shows this. I tried adding a model alias to resolve this but it did not prevent wiping out the previously set __fields variable between models for some reason.

**Comment by nathanaelkane** [comment]
I'm having the exact same issue, I have a Document & an Image model that both actAs MeioUpload.

**Comment by ProLoser** [comment]
This issue mainly creates errors when multiple models are loaded at the same time (via $uses or CR::init) that both make usage of the MeioUpload behavior.

**Comment by jrbasso** [comment]
Dadosordi has implemented this feature in your repo. I merged to this repo: http://github.com/jrbasso/MeioUpload/commit/7a1c46b866151f2892f62dccb3239e569ce552f0

Thanks for the issue.
