### ISSUE TITLE
Wiki text 'INstallation' is refering to the old URL

### ISSUE THREAD

**Issue by primeminister** [jrbasso/MeioUpload#13]
Installation

```
* Clone from github : in your behaviors directory type git clone git://github.com/josegonzalez/MeioUpload.git plugins/meio_upload
```

Must be:
Clone from github : in your behaviors directory type git clone git://github.com/jrbasso/MeioUpload.git plugins/meio_upload

**Comment by jrbasso** [comment]
Fix installation url in readme. Thanks to primeminister. Closed by b02bc3a9c476b53ac3420f8731bfad29f95c8899.
