### ISSUE TITLE
How to turn validation off for the upload field completely

### ISSUE THREAD

**Issue by primeminister** [jrbasso/MeioUpload#15]
He,
Uploading is not required fro my form. How can I turn it off? Without merging with the defaultValidations?

**Comment by primeminister** [comment]
Already found it:
Add this to my model validation array:
'avatar' => array(
            'Empty' => array(
                'check' => false
        ))

**Comment by josegonzalez** [comment]
We should probably add this documentation somewhere. Closing this for now :)

**Comment by bwiggs** [comment]
For anyone else trying to get this to work. You have to make the validation array exactly as written above. "Empty" ... 'check' => false
