### ISSUE TITLE
Doesn't handle multiple joins between same models for Folder Tokens

### ISSUE THREAD

**Issue by ProLoser** [jrbasso/MeioUpload#2]
I have a record which hasMany images, but it also belongsTo 1 primary image (aliased), however whenever I add an image, instead of placing the images into a folder with the number {record_id} it literally uses the folder '{record_id}' instead. Same thing for {id}, which was the first time I noticed it. I have a feeling it's caused by the alias and multi-join. May need to look into it some more though.

**Comment by josegonzalez** [comment]
It currently only handles the following tokens for placing the images in the proper place:
`{model}, {field}, {DS}`

There is not currently a way to do app/webroot/uploads/post/1/image.png, where post is the model name and 1 is the name of the record. However, this is being looked at in my experimental branch (currently at version 1.9.1) and I will update this issue when it has been resolved.

**Comment by josegonzalez** [comment]
Resolved in latest update. As long as $this->data[$model->alias] contains the field, we can map it in the rename. Will not work for habtm nor hasOne or hasMany relationships, only belongsTo. But will also work for any other field in that array.

**Comment by jrbasso** [comment]
As Jose Gonzalez sayed. This solved and pushed.
