### ISSUE TITLE
default setting for max/min width/height in options conflicts with default validations

### ISSUE THREAD

**Issue by randallj2877** [jrbasso/MeioUpload#22]
....the default setting for max/min width/height in options conflicts with default validations...so one would think the default option value (zero) would disable those validations, but they don't...at least according to my tests...

```
var $defaultOptions = array(
    'length' => array(
        'minWidth' => 0, // 0 for not validates
        'maxWidth' => 0,
        'minHeight' => 0,
        'maxHeight' => 0
    )
);

var $defaultValidations = array(
    'MinWidth' => array(
        'rule' => array('uploadCheckMinWidth'),
        'check' => true,
        'last' => true
    ),
    'MaxWidth' => array(
        'rule' => array('uploadCheckMaxWidth'),
        'check' => true,
        'last' => true
    ),
    'MinHeight' => array(
        'rule' => array('uploadCheckMinHeight'),
        'check' => true,
        'last' => true
    ),
    'MaxHeight' => array(
        'rule' => array('uploadCheckMaxHeight'),
        'check' => true,
        'last' => true
    ),
);
```

**Comment by jrbasso** [comment]
In each validation is tested if the value is greater than zero. If not, is returned true, as if the rule is disabled. Other words, will have no problem in checking if you use the default values.

**Comment by josegonzalez** [comment]
Can you attach a model that replicates your tests? Or maybe a testcase?

**Comment by randallj2877** [comment]
There's not much to replicate...my actAs attribute is as follows:

```
var $actsAs = array(
    'MeioUpload.MeioUpload' => array(
        'header_image_file' => array(
            'dir' => '/home/yucelh/category_header_images',
            'create_directory' => false,
            'allowed_mime' => array('image/jpeg', 'image/pjpeg', 'image/gif', 'image/png'),
            'allowed_ext' => array('.jpg', '.jpeg', '.png', '.gif'),
            'thumbnails' => false
        )
    )
);
```

So I'm relying on the "0" default values declared in the behavior file. With those defaults set, I was still forced to switch 'check' to 'false' for the noted validations in order to turn them off...To me, this seems like an extra step...maybe I'm doing something wrong

**Comment by randallj2877** [comment]
In other words they're off by default in the options, but on by default in the validations...
