### ISSUE TITLE
Error on upload when edit record table.

### ISSUE THREAD

**Issue by georgecp** [jrbasso/MeioUpload#27]
I'm using the latest version of the plugin, and am finding error in time to edit my table when I upload the file appears invalid file message, and I'm using a .Jpg. To edit controller, I need to do something different ?

**Comment by josegonzalez** [comment]
Can you paste your model code so that we may take a look at your issue?

**Comment by jrbasso** [comment]
Can you test after the fix of ticket #29? (Commit 22811c5)
I think that it's solve your problem.

**Comment by jrbasso** [comment]
6 months and no answer... closing.
