### ISSUE TITLE
Thumbnails not being marked for deletion, only the normal file.

### ISSUE THREAD

**Issue by halles** [jrbasso/MeioUpload#28]
I suppose the correct behaviour is to delete the thumbs as well, since there would not be any record on database for the file anyway.

This is the code that is working for me at least:

/**
- Set a file to be removed in afterSave() callback
  *
- @param $fieldName String
- @return null
- @author Vinicius Mendes
  */
    function _setFileToRemove(&$model, $fieldName) {
        $filename = $model->field($fieldName);
        if (!empty($filename) && $filename != $this->__fields[$model->alias][$fieldName]['default']) {
            foreach($this->__fields[$model->alias][$fieldName]['thumbsizes'] as $key => $sizes){
                if($key != 'normal')
                    $subpath = DS.'thumb'.DS.$key;
                else
                    $subpath = '';
                $this->__filesToRemove[] = array(
                    'field' => $fieldName,
                    'dir' => $this->__fields[$model->alias][$fieldName]['dir'].$subpath,
                    'name' => $filename
                );
            }
        }
    }

**Comment by jrbasso** [comment]
Removing thumbs when remove main file. Closed by 867acd360eb09f05126c827b1b49a23496ac90b5.

**Comment by jrbasso** [comment]
Thanks for you patch. I modified some things.
