### ISSUE TITLE
$model undefined in _markForDeletion function

### ISSUE THREAD

**Issue by frederic** [jrbasso/MeioUpload#29]
i had some problems to get _markForDeletion working...
These modifications solved my problem.

line 621,7 +621,7
- $this->_markForDeletion($model->alias, $model->primaryKey, $fieldName, $data, $options['default']);
- $this->_markForDeletion($model, $model->alias, $model->primaryKey, $fieldName, $data, $options['default']);

line 1112,7 +1112,7 
-   function _markForDeletion($modelName, $modelPrimaryKey, $fieldName, $data, $default) {
-   function _markForDeletion(&$model, $modelName, $modelPrimaryKey, $fieldName, $data, $default) {

**Comment by jrbasso** [comment]
Fix invalid use of model. Closed by 22811c5927997ec50607dd3b3e35dff656bb8f78.
