### ISSUE TITLE
Syntax error, unexpected T_VARIABLE in meio_upload.php (line 909)

### ISSUE THREAD

**Issue by joelpet** [jrbasso/MeioUpload#3]
Current version contains a syntax error (unexpected T_VARIABLE) in meio_upload.php on line 909:

```
$params = array_merge(
    array(
        'thumbWidth' => 150, 
        'thumbHeight' => 225, 
        'maxDimension' => '')
        $params);
```

I guess it should read (note the comma after array ending parenthesis):

```
$params = array_merge(
    array(
        'thumbWidth' => 150, 
        'thumbHeight' => 225, 
        'maxDimension' => ''),
        $params);
```

**Comment by jrbasso** [comment]
This issue has resolved with merge of others peoples.

**Comment by joelpet** [comment]
My bad, sorry for that.

**Comment by jrbasso** [comment]
When you opened the issue the problem still existed. In the night I merged. Thanks for your report.

**Comment by joelpet** [comment]
Ah, I see. I'm somewhat new to this whole thing with VCS, git and github. :)
Let me go a little off topic and say what a wonderful piece of plugin this is. I had been struggling with file upload components and custom code scanning directories for images when this behaviour appeared and solved everything in a twinkling. Great work!

**Comment by jrbasso** [comment]
Thank you, but thanks to Vinicios Mendes (vbmendes). He is the father of the child. :P
