### ISSUE TITLE
fixName method, unicode

### ISSUE THREAD

**Issue by jimiyash** [jrbasso/MeioUpload#31]
This line in the fixName method changes unicode filenames (japanese characters in my case into -1, 1, 2, etc.)

$filename = Inflector::slug($filename);

**Comment by jrbasso** [comment]
Many methods in the cake using this function to create the files. Have you had problems with them too? If I remove this, I can create other problems for files not supported by the operating system.

**Comment by jimiyash** [comment]
http://book.cakephp.org/view/572/Class-methods
Slug converts special characters into latin versions and converting unmatched characters and spaces to underscores. The slug method expects UTF-8 encoding.

I have used the inflector methods before but never on file names, only English words I know will only contain English. It would be nice if everything was UTF-8, but that is just not reality, for example Microsoft does not use UTF-8 for Japanese, it uses Shift-JIS. 

It would be enough if there was an option to not use the fixName method, just like how you have an option to not check for max width/height, etc. Otherwise I have to comment out the fixName call.

**Comment by jrbasso** [comment]
Right. I will put this on roadmap of 2.2 version. Maximum in the weekend this will be implemented.

**Comment by jrbasso** [comment]
I implemented this on commit 2af28d0f1dd42cbb1957763f4669d8d5c5ce67f4 (branch 2.2).

**Comment by jimiyash** [comment]
Great Work!

**Comment by jrbasso** [comment]
Nice. I'm closing this ticket.
