### ISSUE TITLE
Thumbnails are not deleted because "thumb" is missing in the path.

### ISSUE THREAD

**Issue by TheRec** [jrbasso/MeioUpload#35]
Seems like there is a problem in "_deleteFiles". The part where thumbnail gets deleted do not include the default "thumb" dir in the path. Here's the loop that is in charge of this task in "_deleteFiles".

```
foreach ($this->__fields[$model->alias][$field]['thumbsizes'] as $size => &$config) {
  $file = &new File($dir . DS . $size . DS . $filename);
  $file->delete();
}
```

The path should be corrected like this maybe :
      $file = &new File($dir . DS . 'thumb' . DS . $size . DS . $filename);
Or maybe it might be a bit more complex, because "folderAsField"... at least the above correction will solve the problem when using the default settings.

**Comment by jrbasso** [comment]
Fixing delete of thumbs on delete record. Closed by 20f0fcc07747222f92c0139d2657acb2d886df08.
