### ISSUE TITLE
Original file is not set to be deleted in _setFileToRemove when 'thumbsizes' is not empty

### ISSUE THREAD

**Issue by TheRec** [jrbasso/MeioUpload#36]
When updating a record (either with $field['filename']['remove'] or when "replacing" file) the MeioUploadBehavior::_setFileToRemove method is called and fills MeioUploadBehavior::__filesToRemove attribute with the file(s) to remove in the afterSave callback. 

But in this function, the original file is only added if there is no values in the 'thumbsize'. See the code below (extracted from MeioUploadBehavior::_setFileToRemove) :
    if (empty($this->__fields[$model->alias][$fieldName]['thumbsizes'])) {
      $this->__filesToRemove[] = array(
        'field' => $fieldName,
        'dir' => $this->__fields[$model->alias][$fieldName]['dir'],
        'name' => $filename
      );
      return;
    }
When there are thumbnail, they get deleted by the code right after that (because ['thumbsizes'] is not empty), but the original file is not deleted.

I think we could remove the condition above and add the original file to the MeioUploadBehavior::__filesToRemove attribute in both cases (no matter if ['thumbsizes'] is empty or not) as the goal of the method is to set all the files related to the original file (the one in the record) to be deleted.

**Comment by TheRec** [comment]
Oh.. or instead maybe move this condition to check if the 'thumbsizes' array is empty under, right before we iterated over this array to add each thumbnail file to the MeioUploadBehavior::__filesToRemove attribute.

**Comment by jrbasso** [comment]
Remove original file if have thumbs. Closed by 3645606bf8f0e96e022c086b0b6950b9b6048864.
