### ISSUE TITLE
Nullify the dataFields when the image is removed.

### ISSUE THREAD

**Issue by TheRec** [jrbasso/MeioUpload#37]
In MeioUploadBehavior::_uploadFile, when an image is set to be removed, the meta-data fields and the field itself are not empited because of this part of code (which indeed seems to do what other part of the app should already do, anyways this could be fixed here already and maybe investigate where how to avoid the reptition).
    foreach ($this->__fields[$model->alias] as $fieldName => $options) {
      // Take care of removal flagged field
      // However, this seems to be kind of code duplicating, see line ~711
      if (!empty($data[$model->alias][$fieldName]['remove'])) {
        $this->_markForDeletion($model, $fieldName, $data, $options['default']);
        $data = $this->_unsetDataFields($model->alias, $fieldName, $data, $options);
        $result = array('return' => true, 'data' => $data);
        continue;
      }

The use of _unsetFataFields is improper because not setting a field in the UPDATE query will not empty its value, it will just leave it as is... what we want to do is nullify all the data fields, but they have to be present in the $data variable to be reset.

This would be a solution that would nullify fields specified in the $options['fields'] only if they really exist in the model :
    /**
     \* Sets as NULL data from $data
     \* Useful when deleting a file.
     *
     \* @param $model Reference to model
     \* @param $fieldName string name of field that holds a reference to the file
     \* @param $data array
     \* @param $options array
     \* @return array
     \* @author Jose Diaz-Gonzalez
     **/
      function _nullifyDataFields(&$model, $fieldName, $data, $options) {
        $data[$model->alias][$fieldName] = null;
        foreach ($options['fields'] as $upload_key => $field) {
          if ($model->hasField($field)) {
            $data[$model->alias][$field] = null;
          }
        }
        return $data;
      }

**Comment by jrbasso** [comment]
Nullifing fields on remove. Closed by 01ffbbdbd054b88cf439d3ecb6cf72fd9b2f16b7
