### ISSUE TITLE
Delete does not actualy deletes files

### ISSUE THREAD

**Issue by fralik** [jrbasso/MeioUpload#38]
I am using latest commit for now (http://github.com/jrbasso/MeioUpload/commit/3645606bf8f0e96e022c086b0b6950b9b6048864). The thing is if one run $this->Model->delete($id), then files are not deleted. They are marked for deletion, but since there is no "afterDelete" method nothing happens.

To fix this, simple add function "afterDelete" with same functionality as "afterSave".

**Comment by jrbasso** [comment]
Delete files on delete record. Closed by 37fabc04e0bd9389a59ddaa2693796d07645a770.
