### ISSUE TITLE
Don't create directories until beforeSave()

### ISSUE THREAD

**Issue by iamcam** [jrbasso/MeioUpload#41]
I noticed that any time a model with this attached behavior is run, the thumbnails directories are created. I think it could be better to call the @_createFolders()@ method from @setup()@ to @_uploadFile()@, when the file is actually getting transferred.

**Comment by iamcam** [comment]
I've run some quick tests and with minor modifications it seems to work fine with the proposed change.

**Comment by jrbasso** [comment]
Fixed (by you :D) at a6c48033946610367c5a.
