### ISSUE TITLE
default value

### ISSUE THREAD

**Issue by simkimsia** [jrbasso/MeioUpload#42]
Hi

i am trying to use the default option. i put in the value as default.jpg. i get an error saying that MeioUploadBehavior Error: The default option must be the filename with extension.

the error message was generated at line 228.

reading through the code, i think but am not sure, that default requires the filename AND the extension eg, default.jpg

hence i think line 227 should be changed from strpos($options['default'], '.') !== false 
to
strpos($options['default'], '.') === false

Please correct me if i am wrong. 

I made that change in my code.

thank you.

**Comment by jrbasso** [comment]
You are right. I'm fixing it. Thanks.

**Comment by jrbasso** [comment]
Fixing check of default option. Closed by dc7dd8da71ee27b31a9e7762572c31251a1e2fe8.
