### ISSUE TITLE
undefined index $field in line 713 in meio_upload.php

### ISSUE THREAD

**Issue by simkimsia** [jrbasso/MeioUpload#43]
$result = array('return' => false, 'reason' => 'validation', 'extra' => array('field' => $field, 'error' => $copyResults));

should be 

$result = array('return' => false, 'reason' => 'validation', 'extra' => array('field' => $fieldName, 'error' => $copyResults));

please correct me if i am wrong

**Comment by jrbasso** [comment]
Fixing invalid name of variable. Closed by ccf5ceeeb731e16d6caa5687ecb0ebdbea6c5779.
