### ISSUE TITLE
Need to disable validation for uploadCheckUploadError

### ISSUE THREAD

**Issue by simkimsia** [jrbasso/MeioUpload#46]
Hi there, 

i need to disable this validation function for my extension MeioDuplicate, otherwise i cannot properly save the model.

I of course can do a save($data, array('validate'=>false)), but i was wondering if there is a way to disable a particular validation on the fly.

Thank you.

**Comment by jrbasso** [comment]
I think that you cant do that. I want implement a new method to enable/disable validations to it.

**Comment by simkimsia** [comment]
okie thanks. I had an issue with the MeioDuplicate when i want to save the model with the duplicate image. but i got around it with callbacks and validate set as false. not the best way out. but thanks for reply.

**Comment by josegonzalez** [comment]
MeioDuplicate is not this plugin, sorry.

Regardless, you can do something like the following

```
unset($this->Model->validate['validation_rule_you_hate'])
```

And that should disable the particular validation rule for the duration of the request.

**Comment by simkimsia** [comment]
hi jose, yes i know that this is NOT MeioDuplicate. I wrote it to extend the functionalities of MeioUpload but ran into some problems with the MeioUpload validation rules.

i was just asking to see if there is a way i can improve the code inside MeioDuplicate hence my questions posed to MeioUpload .

you have given me an idea. i will try it later this week. if it works, that would be super. if not, then at least i learn something new.

Thank you Jose. Have a good week!
