### ISSUE TITLE
Warnings trip "Cannot modify header information" issue

### ISSUE THREAD

**Issue by frifox** [jrbasso/MeioUpload#48]
Uploading an image, get PHP warning:
- Missing argument 1 for MeioUploadBehavior::_deleteFilesList(), called in ...... /app/models/behaviors/meio_upload.php on line 318 and defined [APP/models/behaviors/meio_upload.php, line 300]

which triggers:
- Cannot modify header information - headers already sent by...

Trying to do a redirect after add/edit/delete/etc actions but those warnings mess it up. Not good.

**Comment by frifox** [comment]
fixed that by changing, lines 318 & 329:
$this->_deleteFilesList();

into:
$this->_deleteFilesList($model);

**Comment by jrbasso** [comment]
Missing parameter on the last commit. Closed by 5351d652cd78f8365ace6a5d0fdd1e58ef372273
