### ISSUE TITLE
Logical fault concerning maxDimension?

### ISSUE THREAD

**Issue by joelpet** [jrbasso/MeioUpload#5]
Shouldn't the if statement on line (769) in models/behaviors/meio_upload.php read like this:
    if (($params['maxDimension'] != 'h') && ($params['maxDimension'] != 'w'))
instead of:
    if (($params['maxDimension'] != 'h') || ($params['maxDimension'] != 'w'))
?

Otherwise none of the following else cases would never be true, would they?

```
else {
    if ($params['maxDimension'] == 'w') {
        $phpThumb->w = $params['thumbWidth'];
    } else if ($params['maxDimension'] == 'h') {
        $phpThumb->h = $params['thumbHeight'];
    }
}
```

**Comment by jrbasso** [comment]
Really. I changed this in my master. Thanks.
