### ISSUE TITLE
Parse error at line 1145

### ISSUE THREAD

**Issue by ghost** [jrbasso/MeioUpload#53]
While using the console for baking Views and Controller the following alert occurred:

Parse error: parse error, expecting `T_VARIABLE' or`'$'' in /htdocs/plugins/meio_upload/models/behaviors/meio_upload.php on line 1145
- @version 2.1
- @lastmodified 2010-01-03
  1144        foreach ($this->__fields[$model->alias][$field]['thumbsizes'] as $size => &$config) {
  1145            $file = &new File($dir . DS . $size . DS . $filename);
  1146            $file->delete();
  1147        }

Maybe I am blind, but I am unable to get it. Any ideas?

**Comment by jrbasso** [comment]
Are you using PHP 4? Try remove & from line 1145 and see if solve your problem.

**Comment by ghost** [comment]
I am using PHP Version 5.3.2 in a MAMP 1.9 environment...

**Comment by jrbasso** [comment]
Fixing parse error in some PHP versions. Closed by 6c139c20764b07801405052e22bfb7a46029f89c
