### ISSUE TITLE
delete file bug

### ISSUE THREAD

**Issue by danfreak** [jrbasso/MeioUpload#7]
File deletion doesn't work in version 1.7.1 due to a "continue" at line 1065.

Commenting line 1065 everything works fine.

Dan

**Comment by danfreak** [comment]
I found another problem: after deleting a file, using the model.remove checkbox, the DB fields handled by the meio_upload behavior don't get reset to NULL, but still keep the deleted filename etc

**Comment by jrbasso** [comment]
Thanks. I'm commited the fix.
