### ISSUE TITLE
feature request: regenerate thumbnails

### ISSUE THREAD

**Issue by muszek** [jrbasso/MeioUpload#78]
Imagine this scenario: Mark makes a website, uploads 1000 images and has an 600x400 thumbnail created.  A year later his website's design changes and he now needs thumbs to be 300x200.  It would be great if MeioUpload had a method of regenerating all thumbnails according to current options (delete whatever thumbnails exist right now and create new ones).  Optionally the deletion part could be done manually (in case it would be a problem, as thumbnail type names are no longer in the options array).

What do you think?  It's the second time I find myself in need for this kind of functionality.

**Comment by muszek** [comment]
Can I please get some response?  Maybe a code for my Image model that would do the trick?  I'd be really grateful...

**Comment by josegonzalez** [comment]
It would be nice if you implemented such a feature in your fork. That would also be quite awesome. The source _IS_ available ;)

**Comment by muszek** [comment]
I tried doing it on my own, but the code was hard to understand (this says more about me than about the code, don't get me wrong :) ).

**Comment by joshuapaling** [comment]
It's probably a bit late to be of use to you, muszek, but I've added this feature and sent a pull request to jrbasso

**Comment by jrbasso** [comment]
Merged the @joshuapaling pull request. It is available now.
