### ISSUE TITLE
Thumbnail sizes in default 'thumbsizes' always created

### ISSUE THREAD

**Issue by joelpet** [jrbasso/MeioUpload#8]
Since some recent update, it seems like the thumbnails 'small', 'medium' and 'large' (defined in $MeioUpload->defaultOptions['thumbsizes']) are always created no matter what I specify in my model. E.g. I only want 'normal' and 'small' to be created, but 'large' and 'medium' are also made despite my wishes. 

I commented out the defaultOptions for the three default sizes, which solved the problem, which I don't believe introduced any new issues.

By the way, shouldn't 'normal' thumbsizes go into 'dir' directly and not in 'thumb/normal'?

**Comment by jrbasso** [comment]
You tried with master version?

**Comment by joelpet** [comment]
I did a fresh `git clone git://github.com/jrbasso/MeioUpload.git app/plugins/meio_upload`, which I presume should give me the master version. Is that correct?

You might want to have a look at my "test" in http://github.com/jrbasso/MeioUpload/issues#issue/6/comment/41907. That same fixture gives me all the thumbnail directories, despite the configuration which only specifies the 'normal' thumbsize.

**Comment by jrbasso** [comment]
Thanks, I will simulate this. To have the master version can be with git clone (as you say) or, if your project using git, git submodule.
One thing: the master is not always the most stable version. And you need apply git pull some times in the clone.

**Comment by josegonzalez** [comment]
Seems to be a problem with $this->_arrayMerge(). Will look into this shortly.

**Comment by primeminister** [comment]
jose: Does my fix in _arrayMerge() solve this issue?

**Comment by josegonzalez** [comment]
Pulled in his changes from Issue #6. In retrospect, it makes little sense to force someone to generate thumbnails. From now on, the user must specify each thumbnail size and quality if they would like to create a thumbnail. Closing.

**Comment by josegonzalez** [comment]
closed by 37c5ba6cb6201ef5852a7562553bdd3696f06623

**Comment by josegonzalez** [comment]
Woops, this wasn't closed :)
