### ISSUE TITLE
last commit by CauanCabral doesn't work

### ISSUE THREAD

**Issue by riotera** [jrbasso/MeioUpload#82]
He added the folderPermission and filePermission options. These options have read by _createFolders and _copyFileFromTemp functions in the wrong way. The $settings global variable is never set.

I solve the problem adding a parameter ($folderPermission, $filePermission) to the two functions that it is passed in _uploadFile function

**Comment by CauanCabral** [comment]
You are right, I've done changes in support of file and folder permissions to work without attribute ModelBehavior::settings.

New code: https://github.com/jrbasso/MeioUpload/pull/83

Thank's

**Comment by riotera** [comment]
Feliz em poder ajudar

**Comment by jrbasso** [comment]
Thank you, guys.
