### ISSUE TITLE
Does this plugin support multiple file uploads ?

### ISSUE THREAD

**Issue by steinkel** [jrbasso/MeioUpload#86]

**Comment by jrbasso** [comment]
Yes

**Comment by steinkel** [comment]
Hi again. I've installed the component correctly and there are only 1 file per "file" field defined in the model. I was looking for a "multiple uploads" behavior, so you mark one or several files, and the component uploads all the files and saves them, after that it associates the files (on another table) to the model on save.

But this is not the way this behaviour works isn't it ?

Thank you, excellent work.

**Comment by steinkel** [comment]
By the way, the readme says to git clone inside the "behaviours" folder, but maybe it should say to clone inside "plugins" folder. Thanks

**Comment by jrbasso** [comment]
No, the behavior support multiple uploads but to different fields. Sorry...

Thanks for the information about the clone, I fixed.
